export const INSERT_LOGIN = "INSERT_LOGIN"; 
export const INSERT_LOGIN_SUCCESS = "INSERT_LOGIN_SUCCESS"; 
export const INSERT_LOGIN_ERROR = "INSERT_LOGIN_ERROR"; 

export const RESET_INSERT_LOGIN = "RESET_INSERT_LOGIN"; 
export const RESET_INSERT_LOGIN_SUCCESS = "RESET_INSERT_LOGIN_SUCCESS"; 
export const RESET_INSERT_LOGIN_ERROR = "RESET_INSERT_LOGIN_ERROR"; 

export const SIGNUP_DATA = "SIGNUP_DATA"; 
export const SIGNUP_DATA_SUCCESS = "SIGNUP_DATA_SUCCESS"; 
export const SIGNUP_DATA_ERROR = "SIGNUP_DATA_ERROR"; 

export const RESET_INSERT_SIGNUP_DATA = "RESET_INSERT_SIGNUP_DATA"; 
export const RESET_INSERT_SIGNUP_DATA_SUCCESS = "RESET_INSERT_SIGNUP_DATA_SUCCESS"; 
export const RESET_INSERT_SIGNUP_DATA_ERROR = "RESET_INSERT_SIGNUP_DATA_ERROR"; 